feat(core): upgade to laravel 10
carbonaut/boilerplate-api-laravel pull request #12
Opened 2023-05-12 21:57 UTC by eapacheco

## Checklist
- [ x ] Branched the code from the correct base branch; `main`
- [ x ] Used descriptive commit messages [(example)](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit);
- [ ] Updated the documentation according to the introduced changes;
- [ ] Documented all endpoint changes and additions;
- [ ] Added relevant tests to the code introduced by this PR;
- [ ] Created indexes, where necessary, on the migrations that were added, especially on FKs;
- [ ] Added a Factory and a Policy for every model introduced by this PR;

2023-05-12 21:59 UTC, eapacheco commented on app/Enums/EnumTrait.php
> +    public static function asSelect(): array
Laravel ecosystem usually goes with minimalist names, when possible.

2023-05-12 21:59 UTC, eapacheco commented on app/Enums/EnumTrait.php
> +            $array[$case->value] = $case->label();
See my proposal on `::label`

2023-05-12 22:01 UTC, eapacheco commented on app/Enums/EnumTrait.php
> +        return static::getLabel($this) ?: $this->name;
I suggest removing the `null` return option and using the `name` as default.

2023-05-12 22:04 UTC, eapacheco commented on app/Exceptions/Handler.php
> +                error: config('app.debug') && !App::runningUnitTests() ? $error : $e->getMessage(),
Notice the change.
- As from my experience on other projects, having lots of log items with the same 'Server Error' message is very frustrating.
- I think Exception::getMessage is intended to be a end-user allowed message (although they might not understand it at all), then privacy would not be an issue

2023-05-12 22:05 UTC, eapacheco commented on app/Exceptions/TranslatableException.php
> +        bool $messageTranslatable = true,
Again with the minimalist naming preference on `messageTranslatable`

2023-05-12 22:08 UTC, eapacheco commented on app/Http/Controllers/Controller.php
> +class Controller extends BaseController
Came with Laravel 10, their stub for `make:controller` also uses it

2023-05-12 22:10 UTC, eapacheco commented on app/Http/Middleware/EnsureEmailIsVerified.php
> +class EnsureEmailIsVerified
I'm suggesting overriding the original built-in `EnsureEmailIsVerified` (as we already do) but keeping its name -- as Laravel Ecosys usually does when they override a `Base*` class.

2023-05-12 22:11 UTC, eapacheco commented on app/Http/Middleware/EnsureEmailIsVerified.php
> +                403,
422 -> The data on the request is invalid
403 -> User does not have permission (this is the usual status for this scenario)

2023-05-12 22:16 UTC, eapacheco commented on app/Http/Requests/Api/Auth/PostLoginRequest.php
> +            $email = is_string($email) ? $email : '';
`strval` and `larastan` are no longer friends.

<img width="848" alt="Screenshot 2023-05-12 at 19 16 11" src="https://github.com/carbonaut/boilerplate-api-laravel/assets/18501540/4192bc6a-e14a-4f87-8147-5cf9a19d4e4a">

2023-05-12 22:19 UTC, eapacheco commented on app/Http/Requests/Api/Resources/GetLanguageLinesRequest.php
> +    public function all($keys = null)
`parent::all` does not type its return

2023-05-12 22:20 UTC, eapacheco commented on app/Http/Resources/BaseResource.php
> +    protected static function newCollection($resource)
This is a more simple and canonic approach to overriding the collect base class.

2023-05-12 22:22 UTC, eapacheco commented on app/Http/Resources/Models/LanguageLineResource.php
> +            'text' => $this->resource->getTranslation(App::getLocale()),
I find it counterintuitive to use `handle` here, when we can easily use `text` attribute -- which is the attribute being parsed.

2023-05-12 22:23 UTC, eapacheco commented on app/Mail/User/EmailVerification.php
> +    public function envelope(): Envelope
Laravel 10 `Mailable` structure!

2023-05-12 22:25 UTC, eapacheco commented on app/Policies/LanguageLinePolicy.php
> +    public function viewAny(User $user): bool
Laravel `make:policy` doesn't bother on stating `|\Illuminate\Auth\Access\Response`. So why should we?!

2023-05-12 22:26 UTC, eapacheco commented on app/Providers/AppServiceProvider.php
> +            fn () => Password::min(8)
My suggestion on a default Password rule.
Laravel default: `Password::min(8);`

2023-05-12 22:29 UTC, eapacheco commented on database/factories/LanguageLineFactory.php
> +    public function definition(): array
I went along our preferred practice on other projects and suggested minimalist yet ready-to-use factories.

2023-05-12 22:30 UTC, eapacheco commented on database/migrations/2014_10_12_000000_create_users_table.php
> +            $table->string('language')->default('en');
It is rather convenient using literal values on non-app code! (And makes me not hate the `->value` access)

2023-05-12 22:32 UTC, eapacheco commented on composer.json
> -        "archtechx/enums": "^0.3.1",
This package was only used for the `Lowercase()` rule, which is now built-in Laravel.

2023-05-12 22:32 UTC, eapacheco commented on composer.json
> -        "caneara/axiom": "^3.2",
This package was only used for the `Lowercase()` rule, which is now built-in Laravel.

2023-05-12 22:33 UTC, eapacheco commented on composer.json
> -        "staudenmeir/belongs-to-through": "^2.12"
As it was not being used, I removed it and added to the Package Recommendations section of the README

2023-05-12 22:34 UTC, eapacheco commented on composer.json
> -        "spatie/eloquent-sortable": "^4.0",
As it was not being used, I removed it and added to the Package Recommendations section of the README

2023-05-12 22:37 UTC, eapacheco commented on tests/Feature/Api/Resources/GetLanguageLinesByGroupTest.php
> -    private const Method = 'GET';
I don't see the need of a `::Method` const when the Resource itself states the it is a GET endpoint.
I would still use the `::Method` when the SUT doesn't make it clear.

2023-05-12 22:39 UTC, eapacheco commented on tests/Feature/Api/Resources/GetLanguageLinesByGroupTest.php
> -        $this->assertDatabaseHas('language_lines', ['group' => 'api']);
Personally, I believe we should trust that the factories and the test's refresh behavior did they job well. This seem like a good practice and make the tests slimmer

2023-05-12 22:40 UTC, eapacheco commented on tests/Feature/Api/Resources/GetLanguagesTest.php
> -     * @dataProvider availableLanguages
No need for a data provider with a single case

2023-05-17 22:02 UTC, andrefedalto requested changes

2023-05-17 22:02 UTC, andrefedalto commented on config/cors.php
> -        // 'https://my.example.domain',
My suggestion is to leave the examples, because this is a boilerplate and the goal is to make it easier to use, so if anyone needs a different setup, the example is commented here already

2023-05-17 22:02 UTC, andrefedalto commented on config/cors.php
> -        // '/my-example-string/',
My suggestion is to leave the examples, because this is a boilerplate and the goal is to make it easier to use, so if anyone needs a different setup, the example is commented here already

2023-05-17 22:02 UTC, andrefedalto commented on tests/CreatesApplication.php
> -     * is called before each test for each data set.
Consider this is a boilerplate, so it's a good practice to add some small orientations to users of it throughout the code

2023-05-17 22:02 UTC, andrefedalto commented on lang/pt_BR.json
Did you update this file using `php artisan lang:update`? I ran this command an am getting different results

2023-05-17 22:02 UTC, andrefedalto commented on lang/pt_BR/auth.php
Did you update this file using `php artisan lang:update`? I ran this command an am getting different results

2023-05-17 22:02 UTC, andrefedalto commented on lang/pt_BR/pagination.php
Did you update this file using `php artisan lang:update`? I ran this command an am getting different results. It's also missing a new `http-statuses.php` file

2023-05-17 22:02 UTC, andrefedalto commented on lang/pt_BR/passwords.php
Did you update this file using `php artisan lang:update`? I ran this command an am getting different results

2023-05-17 22:02 UTC, andrefedalto commented on lang/pt_BR/validation.php
Did you update this file using `php artisan lang:update`? I ran this command an am getting different results

2023-05-17 22:02 UTC, andrefedalto commented on lang/en/validation.php
Make sure you run `php artisan lang:update` to get the latest translations. For example there's a new phrase `lowercase` that is missing here, and is added by the lang updater. When you run the command, all installed languages will be updated, including the english files.

2023-05-17 22:02 UTC, andrefedalto commented on database/factories/UserFactory.php
> +            'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', // password
Add back the language, to make sure we don't create a user with no language. Remember that when you create from a factory it will only save to the database and won't retrieve it, so the `->default('en')` won't be loaded from the database and the language will be null.

Same for `remember_token`, it's part of the original Laravel definition of the UserFactory.

2023-05-17 22:02 UTC, andrefedalto commented on app/Traits/ResolveRouteBinding.php
> +                    $value = Str::isUuid(is_string($value) ? $value : '');
Logic here is wrong. Previously $value would be either a string (if it was a uuid) or null. After the change, it will always be a boolean.

2023-05-17 22:02 UTC, andrefedalto commented on app/Providers/RouteServiceProvider.php
> -
Add this www back. Having the root domain and the www subdomain pointed to the same place is a good practice and we need to define it on our provider.

2023-05-17 22:02 UTC, andrefedalto commented on app/Http/Resources/Models/LanguageLineResource.php
> +     * @return array<string, mixed>
I'd be as specific as possible here. `string|null` should do the job

2023-05-17 22:02 UTC, andrefedalto commented on app/Http/Requests/Api/Auth/PostLoginRequest.php
> +            $email = is_string($email) ? $email : '';
What a bummer

2023-05-17 22:02 UTC, andrefedalto commented on app/Http/Requests/Api/Auth/PostLoginRequest.php
> +            $email = is_string($email) ? $email : '';
I just came across this library https://github.com/webmozarts/assert maybe it can help us with the asserts.

2023-05-17 22:02 UTC, andrefedalto commented on app/Http/Middleware/RedirectIfAuthenticated.php
> -     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Http\Response
Shouldn't we keep the parameters that are missing from the docblock?

2023-05-17 22:02 UTC, andrefedalto commented on app/Http/Middleware/ThrottleLogin.php
> +    public function maxAttempts()
Why the change if the original trait https://github.com/laravel/ui/blob/master/auth-backend/ThrottlesLogins.php still has the method as protected?

2023-05-17 22:02 UTC, andrefedalto commented on app/Http/Middleware/ThrottleLogin.php
> +    public function decayMinutes()
Why the change if the original trait https://github.com/laravel/ui/blob/master/auth-backend/ThrottlesLogins.php still has the method as protected?

2023-05-17 22:02 UTC, andrefedalto commented on app/Http/Middleware/Authenticate.php
> -     * @return null|string
I know it doesn't come by default, but why not improving the docblock? We have improved in other places

2023-05-17 22:02 UTC, andrefedalto commented on app/Enums/EnumTrait.php
> +     * Return the label defined for the enum case.
Remember to update the description stating that when the label is not defined, it falls back to the name

2023-05-17 22:02 UTC, andrefedalto commented on app/Enums/EnumTrait.php
>       * If a label is not defined, the enum name is used instead.
Remember to update the documentation, now it will always return the label.

2023-05-17 22:02 UTC, andrefedalto commented on app/Exceptions/TranslatableException.php
>  class TranslatableException extends Exception
My suggestion is incorporating all the changes we made on the Uniapp project. There was a bug where the message was sent to the parent instead of the error, and it was reporting wrong on Rollbar. We also added a context in case we want to log extra data.

2023-05-17 22:02 UTC, andrefedalto commented on app/Exceptions/Handler.php
>              if ($e instanceof HttpException && App::isDownForMaintenance()) {
This should also be not reportable

2023-05-17 22:02 UTC, andrefedalto commented on app/Http/Kernel.php
>          'localize'            => \App\Http\Middleware\Localize::class,
If you are using the FQN above, then there's no need to add the localize as an alias here. So either revert above to the alias or remove the alias.

2023-05-17 22:02 UTC, andrefedalto commented on app/Console/Kernel.php
> +        $schedule->command(PruneExpired::class, ['hours' => 24])->daily();
I'd keep the code that is suggested by the documentation https://laravel.com/docs/10.x/sanctum#token-expiration. If you follow the documentation and they change the class name or path, it is not a breaking change. But if they do with this refactored command, then it becomes a breaking change and the application crashes.

2023-05-17 22:02 UTC, andrefedalto commented on README.md
> +- [Eloquent Sortable](https://github.com/spatie/eloquent-sortable) that adds sortable behaviour to an Eloquent model.
Eloquent sortable is duplicated

2023-05-17 22:02 UTC, andrefedalto commented on app/Http/Resources/BaseResource.php
> +    protected static function newCollection($resource)
Nice! This method `newCollection` was not available in the previous version, that's why we had to override the whole method.

2023-05-17 22:02 UTC, andrefedalto commented on app/Mail/User/EmailVerification.php
> +    ) {
It's only on parameter, so we can keep in the same line

2023-05-17 22:02 UTC, andrefedalto commented on app/Mail/User/PasswordReset.php
> +    ) {
This can also fit in one line

2023-05-17 22:02 UTC, andrefedalto commented on tests/Feature/Api/Resources/GetLanguagesTest.php
> -     * is called before each test for each data set on this class.
I'd leave this comment as the boilerplate should be helpful for people who are using it. A comment here can save a lot of time for newcommers

2023-05-17 22:02 UTC, andrefedalto commented on tests/Feature/Api/Resources/GetLanguageLinesByGroupTest.php
> -     * is called before each test for each data set on this class.
I'd keep this as well, might be helpful for newcommers

2023-05-17 22:02 UTC, andrefedalto commented on tests/Feature/Api/Resources/GetLanguageLinesByGroupTest.php
> -        $this->assertDatabaseHas('language_lines', ['group' => 'api']);
Agree, but in the case of asserting first if the database is empty there are two cases. On this current test you assume its empty and does not assert emptiness. But on `testReturnsEmptyArrayOnEmptyGroup` you are asserting the database instead of asserting the response is an empty array. So what is the standard, assert empty database or not? Pick one and update the tests accordingly

2023-05-17 22:02 UTC, andrefedalto commented on composer.json
> -        "doctrine/dbal": "^3.4",
`doctrine/dbal` should stay because it provides some necessary operations on migrations, I believe dropping fields, or renaming only work with dbal installed. Otherwise it gives a hard to debug issue

2023-05-17 22:02 UTC, andrefedalto commented on composer.json
> -        "league/flysystem-aws-s3-v3": "^3.3",
I agree to remove `kreait/laravel-firebase` as there's nothing related to firebase or push messages implemented. But please add back `league/flysystem-aws-s3-v3`, even though it says AWS S3, it actually implements the S3 protocol which is widely used to store files. You can use this package with OVH storage, aws s3, cloudflare r2 or any storage that implements the s3 protocol

2023-05-17 22:02 UTC, andrefedalto commented on composer.json
> -        "laravel-lang/publisher": "^14.3",
This is actually a very important tool for devs to add and update languages on their project. So I suggest adding them back. I had a look and [the project was updated](https://laravel-lang.com/installation/), so now you can only install `composer require laravel-lang/common --dev` and the common package will take care of installing all other packages as dependencies.

2023-05-18 18:56 UTC, eapacheco commented on tests/Feature/Api/Resources/GetLanguageLinesByGroupTest.php
> -        $this->assertDatabaseHas('language_lines', ['group' => 'api']);
It seems that I was already checking the response; but indeed I was also checking database emptiness beforehand -- I removed that!

2023-05-18 18:59 UTC, eapacheco commented on config/cors.php
> -        // 'https://my.example.domain',
Accepted

2023-05-18 18:59 UTC, eapacheco commented on config/cors.php
> -        // '/my-example-string/',
Accepted

2023-05-18 18:59 UTC, eapacheco commented on tests/CreatesApplication.php
> -     * is called before each test for each data set.
Accepted

2023-05-18 19:00 UTC, eapacheco commented on lang/pt_BR.json
I did not! Applied.

2023-05-18 19:22 UTC, eapacheco commented on lang/pt_BR/auth.php
Of course I did! You should double check 👀

2023-05-18 19:23 UTC, eapacheco commented on lang/pt_BR/pagination.php
Applied

2023-05-18 19:23 UTC, eapacheco commented on lang/pt_BR/passwords.php
Applied

2023-05-18 19:23 UTC, eapacheco commented on lang/pt_BR/validation.php
Do you think this package knows better portuguese than I???

2023-05-18 19:23 UTC, eapacheco commented on lang/en/validation.php
Applied!

2023-05-18 19:24 UTC, eapacheco commented on database/factories/UserFactory.php
> +            'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', // password
Got it. As I removed them and the factory did not break, I mistakenly assumed they were nullable.
Rolled them back!

2023-05-18 19:41 UTC, eapacheco commented on app/Traits/ResolveRouteBinding.php
> +                    $value = Str::isUuid(is_string($value) ? $value : '');
Important mistake! Nice catch.
Fixed.

2023-05-18 19:43 UTC, eapacheco commented on app/Providers/RouteServiceProvider.php
> -
Applied!

2023-05-18 19:45 UTC, eapacheco commented on app/Http/Resources/Models/LanguageLineResource.php
> +     * @return array<string, mixed>
Applied!

2023-05-18 20:02 UTC, eapacheco commented on app/Http/Requests/Api/Auth/PostLoginRequest.php
> +            $email = is_string($email) ? $email : '';
I played a bit with the structure and I believe it looks good now!
- The idea here is not to throw for invalid emails, as this responsibility belongs to rules()
- But if we do want to throw, we can go with native `assert`! It also has a second parameter for custom exceptions.

2023-05-18 20:04 UTC, eapacheco commented on app/Http/Middleware/RedirectIfAuthenticated.php
> -     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Http\Response
Laravel boilerplate came without it, but why not!

2023-05-18 20:10 UTC, eapacheco commented on app/Http/Middleware/ThrottleLogin.php
> +    public function maxAttempts()
Not really! You are looking at their `master`, but their `4.x` version has it public. I believe we should go with the latest stable version.

2023-05-18 20:18 UTC, eapacheco commented on app/Http/Middleware/ThrottleLogin.php
> +    public function decayMinutes()
Same as `maxAttempts`

2023-05-18 20:19 UTC, eapacheco commented on app/Http/Middleware/Authenticate.php
> -     * @return null|string
Accepted.

2023-05-18 20:19 UTC, eapacheco commented on app/Enums/EnumTrait.php
> +     * Return the label defined for the enum case.
Applied!

2023-05-18 20:25 UTC, eapacheco commented on app/Enums/EnumTrait.php
>       * If a label is not defined, the enum name is used instead.
Applied!

2023-05-18 20:25 UTC, eapacheco commented on app/Exceptions/TranslatableException.php
>  class TranslatableException extends Exception
Ok! Applied!

2023-05-18 20:26 UTC, eapacheco commented on README.md
> +- [Eloquent Sortable](https://github.com/spatie/eloquent-sortable) that adds sortable behaviour to an Eloquent model.
Removed!

2023-05-18 20:27 UTC, eapacheco commented on app/Mail/User/EmailVerification.php
> +    ) {
I was keeping it as Laravel handled over. But I also prefer your suggestion. Applied!

2023-05-18 20:27 UTC, eapacheco commented on app/Mail/User/PasswordReset.php
> +    ) {
Applied!

2023-05-18 20:29 UTC, eapacheco commented on composer.json
> -        "doctrine/dbal": "^3.4",
Applied!

2023-05-18 20:29 UTC, eapacheco commented on composer.json
> -        "league/flysystem-aws-s3-v3": "^3.3",
Applied!

2023-05-18 20:30 UTC, eapacheco commented on composer.json
> -        "laravel-lang/publisher": "^14.3",
Applied!

2023-05-18 20:31 UTC, eapacheco commented on tests/Feature/Api/Resources/GetLanguageLinesByGroupTest.php
> -     * is called before each test for each data set on this class.
Accepted1

2023-05-18 20:32 UTC, eapacheco commented on tests/Feature/Api/Resources/GetLanguagesTest.php
> -     * is called before each test for each data set on this class.
Accepted

2023-05-18 20:33 UTC, eapacheco commented on app/Console/Kernel.php
> +        $schedule->command(PruneExpired::class, ['hours' => 24])->daily();
Accepted

2023-05-18 20:33 UTC, eapacheco commented on app/Http/Kernel.php
>          'localize'            => \App\Http\Middleware\Localize::class,
Applied!

2023-05-18 20:34 UTC, eapacheco commented on app/Exceptions/Handler.php
>              if ($e instanceof HttpException && App::isDownForMaintenance()) {
Applied

2023-05-19 19:39 UTC, andrefedalto approved these changes

2023-05-19 19:39 UTC, merged